version: '3.8'

services:
  # Le serveur Web et PHP
  php:
    build: ./docker/php
    container_name: camagru_php_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db

  # La base de données PostgreSQL
  db:
    image: postgres:15
    container_name: camagru_postgres_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: